[build]
  # Si tu package.json principal está en la raíz, usa solo npm install
  command = "npm install" 
  publish = "public"

[functions]
  directory = "server"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200