[build]
  # Cambiamos el comando para que solo instale lo de la carpeta server
  command = "cd server && npm install"
  publish = "public"

[functions]
  directory = "server"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200